### ISSUE TITLE
Inference with CPU

### ISSUE THREAD

**Issue by ssimontacchi** [dingkeyan93/Intrinsic-Image-Popularity#1]
Very cool paper! Wanted to try your code out and got this error:

> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is >False. If you are running on a CPU-only machine, please use torch.load with >map_location=torch.device('cpu') to map your storages to the CPU.

Is it possible to use your model to run inference with a CPU? Thanks for the help!

**Comment by dingkeyan93** [comment]
OK
