### ISSUE TITLE
Input a list of image paths

### ISSUE THREAD

**Issue by juliechoong** [dingkeyan93/Intrinsic-Image-Popularity#4]
Is there a way to input a list of image paths instead of manually typing each path? Or is there a way it can read a text file of image paths?

**Comment by Vexeno** [comment]
Delete last "IF" command from "test.py" and paste this. Also, you will probably need to change "path" variable according to your needs.

`if __name__ == '__main__':
    path = "C:\\Users\\Ivan\\Desktop\\Intrinsic-Image-Popularity-master\\INPUT\\"
    directories = os.listdir(path)
    for file in directories:
        image = Image.open(path + file)
        model = torchvision.models.resnet50()
    # model.avgpool = nn.AdaptiveAvgPool2d(1) # for any size of the input
        model.fc = torch.nn.Linear(in_features=2048, out_features=1)
        model.load_state_dict(torch.load('model/model-resnet50.pth', map_location=device)) 
        model.eval().to(device)
        predict(image, model)`

**Comment by juliechoong** [comment]
Thank you so much! It works like a charm now.
